name: push-version
on:
  push:
    tags: ['^[0-9]+\.[0-9]+\.[0-9]+$']
permissions:
  contents: write
env:
  GITHUB_TOKEN: ${{ secrets.WRITABLE_GITHUB_TOKEN }}
jobs:
  commit-and-push-version:
    runs-on: ubuntu-latest
    concurrency:
      group: commit-and-push-version
      cancel-in-progress: false
    steps:
      - name: Checkout 코드
        uses: actions/checkout@main
        with:
          ref: main

      - name: 태그 가져오기
        id: tag
        uses: olegtarasov/get-tag@master

      - name: pyproject.toml 버전 업데이트
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: '^version = "(.+?)"'
          replace: 'version = "${{ steps.tag.outputs.tag }}"'
          include: "pyproject.toml"
          regex: true

      - name: 변경사항 커밋 및 푸시
        uses: stefanzweifel/git-auto-commit-action@master
        with:
          commit_message: "⬆️ 버전 업데이트 (pyproject.toml) v${{ steps.tag.outputs.tag }}"
          branch: main
